### ISSUE TITLE
Cannot reset

### ISSUE THREAD

**Issue by linZHank** [linZHank/turtlebot_rl#1]
```
Traceback (most recent call last):
  File "scripts/ql_nav.py", line 63, in <module>
    observation = env.reset()
  File "/home/linzhank/gym/gym/wrappers/monitor.py", line 37, in reset
    self._before_reset()
  File "/home/linzhank/gym/gym/wrappers/monitor.py", line 185, in _before_reset
    self.stats_recorder.before_reset()
  File "/home/linzhank/gym/gym/wrappers/monitoring/stats_recorder.py", line 68, in before_reset
    raise error.Error("Tried to reset environment which is not done. While the monitor is active for {}, you cannot call reset() unless the episode is over.".format(self.env_id))
gym.error.Error: Tried to reset environment which is not done. While the monitor is active for TurtleBotCrib-v0, you cannot call reset() unless the episode is over.
```

**Comment by linZHank** [comment]
Comment out `env = wrappers.Monitor(env, outdir, force=True)` in `ql_nav.py`
